"""Stable public Python API for conversion, planning, and source plugins."""

from .conversion import ConversionConfig, ConversionResult, convert
from .conversion_types import VideoEncodingConfig
from .distributed import (
    DistributedPlan,
    DistributedStatus,
    JobStore,
    KubernetesScheduler,
    LocalScheduler,
    SchedulerAdapter,
    SlurmScheduler,
    SourceSpec,
    SubmissionResult,
    WorkerConfig,
    agilex_source_spec,
    distributed_status,
    hdf5_source_spec,
    plan_distributed_conversion,
    run_distributed_task,
    try_finalize_distributed_job,
)
from .merge import merge_datasets, plan_merge
from .merge_types import MergeContribution, MergePlan, MergeResult
from .planner import (
    ConversionPlan,
    PerformanceOverrides,
    PlannedConversionResult,
    plan_and_convert,
    plan_conversion,
)
from .plugins import (
    AgileXSource,
    DatasetSource,
    Episode,
    HDF5Mapping,
    HDF5NumericField,
    HDF5Source,
    HDF5VideoField,
    LeRobotV21Source,
    LeRobotV30Source,
    open_dataset,
)
from .source_providers import (
    AgileXSourceConfig,
    AgileXSourceProvider,
    HDF5SourceConfig,
    HDF5SourceProvider,
    LeRobotSourceConfig,
    LeRobotSourceProvider,
    SourceProvider,
    SourceProviderContext,
    SourceProviderRegistry,
    source_providers,
)
from .telemetry import StageMetrics
from .validation import ComparisonReport, ValidationReport, compare_datasets, validate_dataset

__all__ = [
    "AgileXSource",
    "AgileXSourceConfig",
    "AgileXSourceProvider",
    "ComparisonReport",
    "ConversionConfig",
    "ConversionPlan",
    "ConversionResult",
    "DatasetSource",
    "DistributedPlan",
    "DistributedStatus",
    "Episode",
    "HDF5Mapping",
    "HDF5NumericField",
    "HDF5Source",
    "HDF5SourceConfig",
    "HDF5SourceProvider",
    "HDF5VideoField",
    "JobStore",
    "KubernetesScheduler",
    "LeRobotV21Source",
    "LeRobotV30Source",
    "LocalScheduler",
    "LeRobotSourceConfig",
    "LeRobotSourceProvider",
    "MergeContribution",
    "MergePlan",
    "MergeResult",
    "PerformanceOverrides",
    "PlannedConversionResult",
    "StageMetrics",
    "SourceProvider",
    "SourceProviderContext",
    "SourceProviderRegistry",
    "SourceSpec",
    "SubmissionResult",
    "SchedulerAdapter",
    "SlurmScheduler",
    "ValidationReport",
    "VideoEncodingConfig",
    "WorkerConfig",
    "agilex_source_spec",
    "compare_datasets",
    "convert",
    "distributed_status",
    "hdf5_source_spec",
    "merge_datasets",
    "open_dataset",
    "plan_and_convert",
    "plan_conversion",
    "plan_distributed_conversion",
    "plan_merge",
    "source_providers",
    "run_distributed_task",
    "try_finalize_distributed_job",
    "validate_dataset",
]
